name: Build
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: Build artifacts
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        stack: ['2.7.3']
        ghc: ['8.8.4']
        os: [windows-latest] # macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          stack-version: ${{ matrix.stack }}
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          # path: 'C:\Users\runneradmin\AppData\Local\Programs\stack'
          path: ~/.stack
          key: ${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('site.cabal') }}

      - name: Install dependencies
        run: stack install --only-dependencies

      - name: Build
        run: stack build

      - name: Package artifacts
        shell: bash
        run: |
          mkdir package
          dir=$(stack path --dist-dir)/build/site
          cp "$dir/site.exe" ./package/site.exe

      - name: Zip files
        run: |
          Compress-Archive -Path .\package\ -DestinationPath my-hakyll.zip

      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: my-hakyll
          tag_name: my-hakyll-latest
          files: my-hakyll.zip
